server:
  port: 8060

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      hibernate:
        default_schema: management

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: management
