CREATE SCHEMA IF NOT EXISTS MANAGEMENT AUTHORIZATION CLEDA;


CREATE SEQUENCE  EMPLOYEE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE  JOB_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;


CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID            NUMERIC PRIMARY KEY,
    EMPLOYEE_KEY  VARCHAR(250)                        NOT NULL UNIQUE,
    NAME          VARCHAR(250)                        NOT NULL,
    EMAIL         VARCHAR                             NOT NULL,
    PHONE         VARCHAR                             NOT NULL,
    BIRTH_DATE    TIMESTAMP,
    JOB_KEY     VARCHAR                             NOT NULL,
    MATRICULE     VARCHAR                             NOT NULL,
    STATUS        VARCHAR(250)                        NOT NULL,
    CREATED       TIMESTAMP(8) DEFAULT LOCALTIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP(8) DEFAULT LOCALTIMESTAMP NOT NULL,
    CREATED_BY         VARCHAR,
    LAST_MODIFIED_BY   VARCHAR,
    VERSION            NUMERIC
);

CREATE TABLE IF NOT EXISTS JOB
(
    ID            NUMERIC PRIMARY KEY,
    JOB_KEY       VARCHAR(250)                        NOT NULL UNIQUE,
    TITLE         VARCHAR                             NOT NULL,
    DESCRIPTION   VARCHAR(10000)                      NOT NULL,
    CREATED       TIMESTAMP(8) DEFAULT LOCALTIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP(8) DEFAULT LOCALTIMESTAMP NOT NULL,
    CREATED_BY         VARCHAR,
    LAST_MODIFIED_BY   VARCHAR,
    VERSION            NUMERIC
)